export const INITIAL_AUDIT_LOGS = [
  {
    id: 1,
    timestamp: "2026-06-09T08:30:15.120Z",
    operatorId: "DIR-101",
    operatorName: "Noor Azam",
    action: "FACILITY_REGISTRATION",
    details:
      "Registered 'Apex Diagnostic & Wellness Center' under National Health Authority License: IND-KA-9921",
    sourceIp: "192.168.1.10",
    clinicalTemplateVersion: 1,
    integritySignature: "9a2d8f7c...e3f4",
  },
  {
    id: 2,
    timestamp: "2026-06-09T08:35:00.000Z",
    operatorId: "DIR-101",
    operatorName: "Noor Azam",
    action: "DATA_SOVEREIGNTY_RE_ROUTING",
    details:
      "Activated Local Workstation Cryptographic Enclave Storage (Encrypted SQLCipher Database on Desktop Application)",
    sourceIp: "192.168.1.10",
    clinicalTemplateVersion: 1,
    integritySignature: "1c2da4b1...9e8f",
  },
  {
    id: 3,
    timestamp: "2026-06-09T08:42:10.450Z",
    operatorId: "DIR-101",
    operatorName: "Noor Azam",
    action: "CLINICAL_TEMPLATE_REVISION",
    details:
      "Enabled 'Blood Group', 'Allergy Lists' and 'Aadhaar ID' parameters. Activated 'Blood Glucose' & 'Lipid Panel' diagnostic modules.",
    sourceIp: "192.168.1.10",
    clinicalTemplateVersion: 2,
    integritySignature: "3e4fc2d3...0a1b",
  },
  {
    id: 4,
    timestamp: "2026-06-09T09:12:03.110Z",
    operatorId: "REG-204",
    operatorName: "Amit Mishra",
    action: "PATIENT_RECORD_COMMITTED",
    details:
      "Registered Patient File for Aarav Sharma (File Code: PAT-2026-00042) under Schema v2.00",
    sourceIp: "192.168.1.45",
    clinicalTemplateVersion: 2,
    integritySignature: "4f5ad3e4...1b2c",
  },
  {
    id: 5,
    timestamp: "2026-06-09T11:20:45.300Z",
    operatorId: "STF-302",
    operatorName: "Priya Nair",
    action: "DIAGNOSTIC_RESULTS_UPDATED",
    details:
      "Updated Blood Glucose and Lipid Profile metrics for Patient File: PAT-2026-00042",
    sourceIp: "192.168.1.47",
    clinicalTemplateVersion: 2,
    integritySignature: "5b6ec1f2...8a7b",
  },
  {
    id: 6,
    timestamp: "2026-06-09T14:15:22.000Z",
    operatorId: "REG-205",
    operatorName: "Vikram Malhotra",
    action: "PATIENT_RECORD_COMMITTED",
    details:
      "Registered Patient File for Rajesh Kumar (File Code: PAT-2026-00044) under Schema v2.00",
    sourceIp: "192.168.1.46",
    clinicalTemplateVersion: 2,
    integritySignature: "7d8eb2a3...4c5d",
  }
];

export const INITIAL_STAFF = [
  {
    id: "SUP-001",
    name: "Zoya Khan",
    email: "zoya.khan@apexclinical.in",
    role: "Platform Super Admin",
    status: "Active",
    mfa: true,
    specialization: "Network Operations",
  },
  {
    id: "DIR-101",
    name: "Noor Azam",
    email: "noor.azam@apexclinical.in",
    role: "Clinical Director (Admin)",
    status: "Active",
    mfa: true,
    specialization: "Pathology Head",
  },
  {
    id: "REG-204",
    name: "Amit Mishra",
    email: "a.mishra@apexclinical.in",
    role: "Medical Registrar (Staff)",
    status: "Active",
    mfa: false,
    specialization: "Front Desk Operations",
  },
  {
    id: "STF-302",
    name: "Priya Nair",
    email: "p.nair@apexclinical.in",
    role: "Medical Registrar (Staff)",
    status: "Active",
    mfa: true,
    specialization: "Lab Assistant",
  },
  {
    id: "STF-099",
    name: "Robert Langdon",
    email: "r.langdon@apexclinical.in",
    role: "Medical Registrar (Staff)",
    status: "Suspended",
    mfa: false,
    specialization: "Operations Executive",
  },
  {
    id: "STF-303",
    name: "Dr. Ananya Sen",
    email: "a.sen@apexclinical.in",
    role: "Consultant Biochemist (Staff)",
    status: "Active",
    mfa: true,
    specialization: "Clinical Biochemistry",
  },
  {
    id: "REG-205",
    name: "Vikram Malhotra",
    email: "v.malhotra@apexclinical.in",
    role: "Medical Registrar (Staff)",
    status: "Active",
    mfa: false,
    specialization: "Front Desk Operations",
  }
];

export const INITIAL_PATIENT_RECORDS = [
  {
    id: "PAT-2026-00042",
    fullName: "Aarav Sharma",
    dob: "1990-05-14",
    gender: "Male",
    phone: "+91 98765 43210",
    visitDate: "2026-06-09T09:10",
    testRequested: "Routine Coronary Profile",
    storageArchitecture: "LOCAL_ENCLAVE",
    appliedTemplateVersion: 2,
    demographics: {
      bloodGroup: "B+",
      knownAllergies: "Penicillin, Dust Mites",
      emailAddress: "aarav.sharma@gmail.com",
      address: {
        street: "Flat 402, Shanti Kunj, Sector 15, Dwarka",
        city: "Delhi",
        state: "Delhi",
        pincode: "110075",
      },
      nationalId: "[Aadhaar Redacted]",
      insurancePolicy: "HDFC Ergo Optima Secure #90119",
      emergencyContact: "Sunita Sharma (+91 98765 43209)",
    },
    diagnostics: {
      lipidProfile: {
        totalCholesterol: "185",
        hdl: "52",
        ldl: "110",
        triglycerides: "115",
      },
      bloodGlucose: {
        fasting: "92",
        postPrandial: "135",
      },
    },
    customClinicalParameters: {
      "Oxygen Saturation (SpO2)": "98%",
    },
  },
  {
    id: "PAT-2026-00043",
    fullName: "Priyadarshini Patel",
    dob: "1985-11-23",
    gender: "Female",
    phone: "+91 91234 56789",
    visitDate: "2026-06-09T10:05",
    testRequested: "Diabetic Monitoring Study",
    storageArchitecture: "LOCAL_ENCLAVE",
    appliedTemplateVersion: 2,
    demographics: {
      bloodGroup: "A-",
      knownAllergies: "None Reported",
      emailAddress: "priya.patel@clinicalnet.com",
      address: {
        street: "Block C-12, Green Glen Layout, Bellandur",
        city: "Bengaluru",
        state: "Karnataka",
        pincode: "560103",
      },
      nationalId: "[Aadhaar Redacted]",
      insurancePolicy: "Star Health Family Red Carpet",
      emergencyContact: "Karan Patel (+91 91234 56780)",
    },
    diagnostics: {
      bloodGlucose: {
        fasting: "142",
        postPrandial: "210",
      },
    },
    customClinicalParameters: {
      "Oxygen Saturation (SpO2)": "95%",
    },
  },
  {
    id: "PAT-2026-00044",
    fullName: "Rajesh Kumar",
    dob: "1978-08-19",
    gender: "Male",
    phone: "+91 95600 12345",
    visitDate: "2026-06-09T14:10",
    testRequested: "Comprehensive Lipid Evaluation",
    storageArchitecture: "LOCAL_ENCLAVE",
    appliedTemplateVersion: 2,
    demographics: {
      bloodGroup: "O+",
      knownAllergies: "Sulfa Drugs",
      emailAddress: "rajesh.kumar78@yahoo.com",
      address: {
        street: "C-502, Prestige Apartments, Indiranagar",
        city: "Bengaluru",
        state: "Karnataka",
        pincode: "560038",
      },
      nationalId: "[Aadhaar Redacted]",
      insurancePolicy: "Niva Bupa Health Companion",
      emergencyContact: "Renu Kumar (+91 95600 12346)",
    },
    diagnostics: {
      lipidProfile: {
        totalCholesterol: "210",
        hdl: "41",
        ldl: "138",
        triglycerides: "155",
      },
    },
    customClinicalParameters: {
      "Oxygen Saturation (SpO2)": "97%",
    },
  },
  {
    id: "PAT-2026-00045",
    fullName: "Meera Iyer",
    dob: "1993-03-05",
    gender: "Female",
    phone: "+91 81234 98765",
    visitDate: "2026-06-09T15:30",
    testRequested: "Standard Glycemic Status Panel",
    storageArchitecture: "LOCAL_ENCLAVE",
    appliedTemplateVersion: 2,
    demographics: {
      bloodGroup: "AB+",
      knownAllergies: "Dust, Peanuts",
      emailAddress: "meera.iyer93@gmail.com",
      address: {
        street: "A-101, Green Meadows, Sector 4, Vashi",
        city: "Navi Mumbai",
        state: "Maharashtra",
        pincode: "400703",
      },
      nationalId: "[Aadhaar Redacted]",
      insurancePolicy: "Care Health Supreme Policy",
      emergencyContact: "Ramesh Iyer (+91 81234 98760)",
    },
    diagnostics: {
      bloodGlucose: {
        fasting: "105",
        postPrandial: "158",
      },
    },
    customClinicalParameters: {
      "Oxygen Saturation (SpO2)": "99%",
    },
  }
];

export const ROLE_LOGIN_PRESETS = {
  superadmin: {
    email: "zoya.khan@apexclinical.in",
    message: "Superadmin credentials loaded. Click Authenticate Operator.",
  },
  admin: {
    email: "noor.azam@apexclinical.in",
    message: "Admin credentials loaded. Click Authenticate Operator.",
  },
  staff: {
    email: "a.mishra@apexclinical.in",
    message: "Staff credentials loaded. Click Authenticate Operator.",
  },
};

export const ROLE_DASHBOARD_SNAPSHOTS = {
  superadmin: {
    title: "Superadmin SaaS Overview",
    description:
      "Platform-level subscription and access insights across all onboarded clinics.",
    statusText: "SaaS Status: Healthy",
    metrics: [
      {
        id: "users",
        label: "Total Users",
        total: "248",
        totalHint: "Across all facilities",
        yearLabel: "This Year",
        yearValue: "232",
        yearTrend: "+7.1%",
        monthLabel: "This Month",
        monthValue: "24",
        monthTrend: "+11.3%",
      },
      {
        id: "plans",
        label: "Subscribed Clinics",
        total: "24",
        totalHint: "Active subscriptions",
        yearLabel: "Renewed",
        yearValue: "19",
        yearTrend: "+8.4%",
        monthLabel: "New this month",
        monthValue: "3",
        monthTrend: "+12.0%",
      },
      {
        id: "renewals",
        label: "Renewals Due (30d)",
        total: "6",
        totalHint: "Upcoming expiries",
        yearLabel: "Completed",
        yearValue: "41",
        yearTrend: "+10.2%",
        monthLabel: "Pending",
        monthValue: "6",
        monthTrend: "-4.0%",
      },
      {
        id: "expiring",
        label: "Expiring in 7 Days",
        total: "2",
        totalHint: "Immediate attention",
        yearLabel: "Recovered",
        yearValue: "11",
        yearTrend: "+22.0%",
        monthLabel: "At risk",
        monthValue: "2",
        monthTrend: "-12.5%",
      },
    ],
    trendTitle: "Weekly Authentication Traffic",
    trendTag: "Last 7 days",
    trendBars: [44, 52, 49, 58, 61, 56, 47],
    trendFooter: "Only sign-in traffic is shown at platform level.",
    splitTitle: "Plan Distribution",
    splitTotal: "24 facilities",
    splitLegend: [
      { label: "Enterprise Plan", percentage: "46%" },
      { label: "Growth Plan", percentage: "37%" },
      { label: "Starter Plan", percentage: "17%" },
    ],
    splitNote: "Subscription mix by active tenant contracts.",
    planSubscriptions: [
      {
        tenant: "Apex Diagnostic & Wellness Center",
        plan: "Enterprise",
        users: "45/60",
        expiresOn: "2026-12-20",
        status: "Active",
      },
      {
        tenant: "Metro Labs Bengaluru",
        plan: "Growth",
        users: "28/35",
        expiresOn: "2026-08-14",
        status: "Renewal Due",
      },
      {
        tenant: "Horizon Care Pathology",
        plan: "Starter",
        users: "12/15",
        expiresOn: "2026-07-02",
        status: "Expires Soon",
      },
      {
        tenant: "Northline Diagnostics",
        plan: "Growth",
        users: "31/35",
        expiresOn: "2026-09-28",
        status: "Active",
      },
    ],
    streamTitle: "Network Login Audit",
    streamTag: "Login events only",
    stream: [
      "AUTH_SESSION_CREATED: zoya.khan@apexclinical.in signed in from 10.20.1.11.",
      "AUTH_SESSION_CREATED: ops.admin@metrolabs.in signed in from 10.20.1.27.",
      "AUTH_SESSION_CREATED: billing.owner@horizoncare.in signed in from 10.20.1.43.",
    ],
  },
  admin: {
    title: "Facility Operations Monitor",
    description:
      "Clinic-level control room with patient flow, diagnostics usage, and workforce capacity insights.",
    statusText: "Facility Status: Optimal",
    metrics: [
      {
        id: "patients",
        label: "Patient Records",
        total: "584",
        totalHint: "All Patients",
        yearLabel: "This Year",
        yearValue: "184",
        yearTrend: "+24.5%",
        monthLabel: "This Month",
        monthValue: "14",
        monthTrend: "+12.0%",
      },
      {
        id: "staff",
        label: "Staff Strength",
        total: "18",
        totalHint: "Assigned operators",
        yearLabel: "This Year",
        yearValue: "+2",
        yearTrend: "+33.3%",
        monthLabel: "This Month",
        monthValue: "+1",
        monthTrend: "+50.0%",
      },
      {
        id: "revenue",
        label: "Revenue",
        total: "Rs 41.2L",
        totalHint: "Year-to-date",
        yearLabel: "This Year",
        yearValue: "Rs 41.2L",
        yearTrend: "+14.5%",
        monthLabel: "This Month",
        monthValue: "Rs 4.8L",
        monthTrend: "+8.2%",
      },
      {
        id: "tests",
        label: "Diagnostics",
        total: "1240",
        totalHint: "Profiles run",
        yearLabel: "This Year",
        yearValue: "840",
        yearTrend: "+18.5%",
        monthLabel: "This Month",
        monthValue: "124",
        monthTrend: "+12.0%",
      },
    ],
    trendTitle: "Intake Volume Trend",
    trendTag: "Past 7 Days",
    trendBars: [70, 50, 90, 110, 80, 120, 40],
    trendFooter: "Weekly registration load remains within normal limits.",
    splitTitle: "Diagnostic Split",
    splitTotal: "1240 profiles",
    splitLegend: [
      { label: "Blood Glucose Studies", percentage: "60%" },
      { label: "Lipid Profile Panels", percentage: "40%" },
    ],
    splitNote: "Based on active facility configurations.",
    streamTitle: "Admin Terminal Journal",
    streamTag: "Facility scope",
    stream: [
      "STAFF_CREDENTIAL_PROVISIONED: New registrar invited.",
      "PATIENT_RECORD_COMMITTED: New intake successfully saved.",
      "CLINICAL_TEMPLATE_REVISION: Module policy updated.",
    ],
  },
  staff: {
    title: "Staff Workflow Snapshot",
    description:
      "Shift-focused dashboard for intake velocity, pending tasks, and report readiness.",
    statusText: "Shift Status: On Track",
    metrics: [
      {
        id: "myIntake",
        label: "My Registrations",
        total: "26",
        totalHint: "Handled this month",
        yearLabel: "This Week",
        yearValue: "9",
        yearTrend: "+12.5%",
        monthLabel: "Today",
        monthValue: "3",
        monthTrend: "+50.0%",
      },
      {
        id: "pending",
        label: "Pending Follow-ups",
        total: "11",
        totalHint: "Need verification",
        yearLabel: "Resolved",
        yearValue: "17",
        yearTrend: "+9.6%",
        monthLabel: "Escalated",
        monthValue: "2",
        monthTrend: "-18.0%",
      },
      {
        id: "turnaround",
        label: "Avg Turnaround",
        total: "42 min",
        totalHint: "Per registration",
        yearLabel: "Last Week",
        yearValue: "46 min",
        yearTrend: "-8.7%",
        monthLabel: "Target",
        monthValue: "40 min",
        monthTrend: "+4.7%",
      },
      {
        id: "quality",
        label: "Data Accuracy",
        total: "98.4%",
        totalHint: "Validated forms",
        yearLabel: "Corrections",
        yearValue: "5",
        yearTrend: "-21.0%",
        monthLabel: "Rejected",
        monthValue: "1",
        monthTrend: "-50.0%",
      },
    ],
    trendTitle: "My Daily Intake Trend",
    trendTag: "Current week",
    trendBars: [35, 44, 41, 52, 47, 58, 36],
    trendFooter: "Most work arrives between 10:00 and 14:00.",
    splitTitle: "Current Task Mix",
    splitTotal: "37 active tasks",
    splitLegend: [
      { label: "New Registrations", percentage: "54%" },
      { label: "Report Coordination", percentage: "31%" },
      { label: "Patient Calls", percentage: "15%" },
    ],
    splitNote: "Task queue refreshed every 15 minutes.",
    streamTitle: "Shift Activity Feed",
    streamTag: "Assigned to you",
    stream: [
      "INTAKE_COMPLETED: Meera Iyer profile verified.",
      "REPORT_READY: Lipid panel shared with consultant.",
      "FOLLOWUP_SCHEDULED: Patient callback booked for 18:30.",
    ],
  },
};

export const SUPERADMIN_NETWORK_LOGIN_LOGS = [
  {
    id: 2001,
    timestamp: "2026-06-27T08:10:14.000Z",
    operatorId: "SUP-001",
    operatorName: "Zoya Khan",
    action: "AUTH_SESSION_CREATED",
    details: "Platform superadmin authenticated from control console.",
    sourceIp: "10.20.1.11",
    clinicalTemplateVersion: 2,
    integritySignature: "7f9ea1a0...cc24",
  },
  {
    id: 2002,
    timestamp: "2026-06-27T09:05:48.000Z",
    operatorId: "TEN-339",
    operatorName: "Ops Admin - Metro Labs",
    action: "AUTH_SESSION_CREATED",
    details: "Tenant admin authenticated from Bengaluru node.",
    sourceIp: "10.20.1.27",
    clinicalTemplateVersion: 2,
    integritySignature: "8c64bb20...a1c3",
  },
  {
    id: 2003,
    timestamp: "2026-06-27T10:22:33.000Z",
    operatorId: "TEN-552",
    operatorName: "Billing Owner - Horizon Care",
    action: "AUTH_SESSION_CREATED",
    details: "Tenant billing owner authenticated for renewal workflow.",
    sourceIp: "10.20.1.43",
    clinicalTemplateVersion: 2,
    integritySignature: "5aa17dff...bb11",
  },
];